/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#414944",
        "surface-container-high": "#dce9ff",
        "on-background": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "on-error": "#ffffff",
        "on-secondary-container": "#446c44",
        "on-primary-container": "#81b29c",
        "surface-bright": "#f8f9ff",
        "secondary": "#406840",
        "surface-variant": "#d3e4fe",
        "surface-container-low": "#eff4ff",
        "inverse-primary": "#a0d1ba",
        "on-tertiary-fixed": "#001d31",
        "surface-tint": "#396754",
        "on-surface": "#0b1c30",
        "primary-container": "#144534",
        "secondary-fixed-dim": "#a5d2a2",
        "surface-dim": "#cbdbf5",
        "secondary-fixed": "#c1eebc",
        "on-tertiary-fixed-variant": "#004b73",
        "outline-variant": "#c0c9c2",
        "secondary-container": "#beecb9",
        "inverse-on-surface": "#eaf1ff",
        "on-tertiary-container": "#50aef4",
        "on-primary-fixed-variant": "#204f3d",
        "tertiary-fixed-dim": "#93ccff",
        "primary-fixed": "#bbeed5",
        "error": "#ba1a1a",
        "on-primary-fixed": "#002116",
        "tertiary-container": "#004064",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#a0d1ba",
        "tertiary": "#002943",
        "on-secondary-fixed": "#002106",
        "surface": "#f8f9ff",
        "background": "#f8f9ff",
        "tertiary-fixed": "#cce5ff",
        "surface-container": "#e5eeff",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "primary": "#002e20",
        "on-primary": "#ffffff",
        "outline": "#717974",
        "inverse-surface": "#213145",
        "on-secondary-fixed-variant": "#284f2a",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "2rem",
        "space-sm": "0.5rem",
        "margin-mobile": "0.75rem",
        "margin": "1rem",
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "space-md": "0.75rem",
        "gutter-mobile": "0.75rem",
        "space-lg": "1.25rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-xs": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-xs": ["10px", { lineHeight: "12px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "22px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "500" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
